---
title: "AMR-Hub Demo and Discussion"
author: "Keiran Suchak"
date: 2026-01-30
bibliography: references.bib
format:
  revealjs:
    footer: "Keiran Suchak - University of Leeds"
    slide-number: h.v
    chalkboard: true
    mermaid:
      theme: neutral
---

```{python}
import geopandas as gpd
import pandas as pd
```

# Topics

## Topics

```{mermaid}
flowchart LR
    classDef highlight fill:#ffcc00,stroke:#333,stroke-width:2px;

    subgraph Data
        direction TB

        A(Floorplan<br>DWG)
        B(RCD<br>CSV/DB)
        C(Wearables<br>CSV/DB?)

        A --- B
        B --- C
    end

    subgraph Models
        direction TB

        D(ABM)
        E(ML)

        D ~~~ E
    end

    subgraph Outputs
        direction TB

        I(Early warning<br>indicator for<br>infection outbreaks)

        subgraph "Simulation under uncertainty"
            direction TB
            F(Synthetic trajectories)
            G(Co-location / Interaction)
            H(Infection transmission)

            F --> G
            G --> H

        end

    end

    Data --- Models
    Models --- Outputs
```

## Topics - Floorplans

```{mermaid}
flowchart LR
    classDef highlight fill:#ffcc00,stroke:#333,stroke-width:2px;

    subgraph Data
        direction TB

        A(Floorplan<br>DWG):::highlight
        B(RCD<br>CSV/DB):::highlight
        C(Wearables<br>CSV/DB?)

        A --- B
        B --- C
    end

    subgraph Models
        direction TB

        D(ABM):::highlight
        E(ML)

        D ~~~ E
    end

    subgraph Outputs
        direction TB

        I(Early warning<br>indicator for<br>infection outbreaks)

        subgraph "Simulation under uncertainty"
            direction TB
            F(Synthetic trajectories)
            G(Co-location / Interaction)
            H(Infection transmission)

            F --> G
            G --> H

        end

    end

    Data --- Models
    Models --- Outputs
```

## Topics - Problem framing

```{mermaid}
flowchart LR
    classDef highlight fill:#ffcc00,stroke:#333,stroke-width:2px;

    subgraph Data
        direction TB

        A(Floorplan<br>DWG)
        B(RCD<br>CSV/DB):::highlight
        C(Wearables<br>CSV/DB?)

        A --- B
        B --- C
    end

    subgraph Models
        direction TB

        D(ABM)
        E(ML)

        D ~~~ E
    end

    subgraph Outputs
        direction TB

        I(Early warning<br>indicator for<br>infection outbreaks)

        subgraph "Simulation under uncertainty"
            direction TB
            F(Synthetic trajectories):::highlight
            G(Co-location / Interaction):::highlight
            H(Infection transmission):::highlight

            F --> G
            G --> H

        end

    end

    Data --- Models
    Models --- Outputs
```

## Topics - Temporal sequence modelling

```{mermaid}
flowchart LR
    classDef highlight fill:#ffcc00,stroke:#333,stroke-width:2px;

    subgraph Data
        direction TB

        A(Floorplan<br>DWG)
        B(RCD<br>CSV/DB):::highlight
        C(Wearables<br>CSV/DB?)

        A --- B
        B --- C
    end

    subgraph Models
        direction TB

        D(ABM)
        E(ML):::highlight

        D ~~~ E
    end

    subgraph Outputs
        direction TB

        I(Early warning<br>indicator for<br>infection outbreaks):::highlight

        subgraph "Simulation under uncertainty"
            direction TB
            F(Synthetic trajectories)
            G(Co-location / Interaction)
            H(Infection transmission)

            F --> G
            G --> H

        end

    end

    Data --- Models
    Models --- Outputs
```

# Floorplans

## Floorplans

```{mermaid}
flowchart LR
    classDef highlight fill:#ffcc00,stroke:#333,stroke-width:2px;

    subgraph Data
        direction TB

        A(Floorplan<br>DWG):::highlight
        B(RCD<br>CSV/DB)
        C(Wearables<br>CSV/DB?)

        A --- B
        B --- C
    end

    subgraph Models
        direction TB

        D(ABM)
        E(ML)

        D ~~~ E
    end

    subgraph Outputs
        direction TB

        I(Early warning<br>indicator for<br>infection outbreaks)

        subgraph "Simulation under uncertainty"
            direction TB
            F(Synthetic trajectories)
            G(Co-location / Interaction)
            H(Infection transmission)

            F --> G
            G --> H

        end

    end

    Data --- Models
    Models --- Outputs
```

## Floorplans

```{mermaid}
flowchart LR
    classDef highlight fill:#ffcc00,stroke:#333,stroke-width:2px;

    subgraph Data
        direction TB

        A(Floorplan<br>DWG):::highlight
        B(RCD<br>CSV/DB):::highlight
        C(Wearables<br>CSV/DB?)

        A --- B
        B --- C
    end

    subgraph Models
        direction TB

        D(ABM)
        E(ML)

        D ~~~ E
    end

    subgraph Outputs
        direction TB

        I(Early warning<br>indicator for<br>infection outbreaks)

        subgraph "Simulation under uncertainty"
            direction TB
            F(Synthetic trajectories)
            G(Co-location / Interaction)
            H(Infection transmission)

            F --> G
            G --> H

        end

    end

    Data --- Models
    Models --- Outputs
```

## Floorplans - RCD {.smaller}

```{python}
df = pd.read_csv("https://github.com/UCL-ARC/amr-hub/blob/as/agent-creation/python-code/tests/inputs/location_timeseries.csv")
df.head()
```

## Floorplans - RCD

- <a href="http://localhost:8000/ega02.pdf" target="_blank">Floorplan PDF</a>
- Attaching spatial points to RCD
  - `regex`: matching to standardised location tags
  - Medical gas pipes: identifying bed locations on ward

## Floorplans

```{mermaid}
flowchart LR
    classDef highlight fill:#ffcc00,stroke:#333,stroke-width:2px;

    subgraph Data
        direction TB

        A(Floorplan<br>DWG):::highlight
        B(RCD<br>CSV/DB)
        C(Wearables<br>CSV/DB?)

        A --- B
        B --- C
    end

    subgraph Models
        direction TB

        D(ABM):::highlight
        E(ML):::highlight

        D ~~~ E
    end

    subgraph Outputs
        direction TB

        I(Early warning<br>indicator for<br>infection outbreaks)

        subgraph "Simulation under uncertainty"
            direction TB
            F(Synthetic trajectories)
            G(Co-location / Interaction)
            H(Infection transmission)

            F --> G
            G --> H

        end

    end

    Data --- Models
    Models --- Outputs
```

## Floorplans

- `cadflow` docker image:

```{mermaid}
flowchart LR
    subgraph " "
        direction LR
        A(.dwg)
        B(.dxf)
        C(.gpkg)

        A --> B
        B --> C
    end
```
- Visualise

## Floorplans

- <a href="http://localhost:8000/ega02.html" target="_blank">Floorplan HTML</a>
- But this just provides linestrings - we need tagged polygons!
- Potential next steps:
  - Autodesk Revit: Extracting polygons
  - Extension:
```{mermaid}
flowchart LR
    subgraph " "
        direction LR
        B(" ")
        C(.gpkg)
        D(.yaml)

        B --> C
        C --> D
    end
```

# Simulation under uncertainty - problem framing

## Simulation under uncertainty

```{mermaid}
flowchart LR
    classDef highlight fill:#ffcc00,stroke:#333,stroke-width:2px;


    subgraph Data
        direction TB

        A(Floorplan<br>DWG)
        B(RCD<br>CSV/DB):::highlight
        C(Wearables<br>CSV/DB?)

        A --- B
        B --- C
    end

    subgraph Models
        direction TB

        D(ABM)
        E(ML)

        D ~~~ E
    end

    subgraph Outputs
        direction TB

        I(Early warning<br>indicator for<br>infection outbreaks)

        subgraph "Simulation under uncertainty"
            direction TB
            F(Synthetic trajectories):::highlight
            G(Co-location / Interaction):::highlight
            H(Infection transmission):::highlight

            F --> G
            G --> H

        end

    end

    Data --- Models
    Models --- Outputs
```

## Simulation under uncertainty - problem framing

```{mermaid}
flowchart LR
    subgraph " "
        direction LR
        F(Synthetic trajectories):::highlight
        G(Co-location / Interaction):::highlight
        H(Infection transmission):::highlight

        F --> G
        G --> H
    end
```

## Simulation under uncertainty - problem framing

```{mermaid}
flowchart LR
    A(RCD)
    B(Wearables)
    C(Infection data)
    D(Mobility model)
    E(Infection model)
    subgraph " "
        direction LR
        F(Synthetic trajectories)
        G(Co-location / Interaction)
        H(Infection transmission)

        F --> G
        G --> H
    end
    A --> F
    B --> F
    C --> H
    D --> F
    E --> H
```

## Simulation under uncertainty - objectives

- Simulation of mobility between observed locations
- Simulation of behaviour fitted to observed locations

## Simulation under uncertainty - thinking (loosely) in data assimilation terms

- **Sequential assimilation:** Simulation of mobility between observed locations
- **Variational assimilation:** Simulation of behaviour fitted to observed
  locations

## Simulation under uncertainty - problem framing

> Given two observations of a healthcare worker that form the origin and
> destination of a "trip", what is the most likely route / series of activities
> for them to take in-between?

## Simulation under uncertainty - problem framing

> Iterate over sequential pairs of observations for a healthcare worker:
>
>> Given two observations of a healthcare worker that form the origin and
>> destination of a "trip", what is the most likely route / series of activities
>> for them to take in-between?

# Temporal sequence modelling

## Temporal sequence modelling

```{mermaid}
flowchart LR
    classDef highlight fill:#ffcc00,stroke:#333,stroke-width:2px;

    subgraph Data
        direction TB

        A(Floorplan<br>DWG)
        B(RCD<br>CSV/DB):::highlight
        C(Wearables<br>CSV/DB?)

        A --- B
        B --- C
    end

    subgraph Models
        direction TB

        D(ABM)
        E(ML):::highlight

        D ~~~ E
    end

    subgraph Outputs
        direction TB

        I(Early warning<br>indicator for<br>infection outbreaks):::highlight

        subgraph "Simulation under uncertainty"
            direction TB
            F(Synthetic trajectories)
            G(Co-location / Interaction)
            H(Infection transmission)

            F --> G
            G --> H

        end

    end

    Data --- Models
    Models --- Outputs
```

## Temporal sequence modelling - objective

> Develop an analytics pipeline that detects behavioural pre-cursors to
> infection outbreaks and produces an early-warning risk indicator at the
> team/role level.

## Temporal sequence modelling - hypotheses

- **H1: Behaviour** - Specific short-term behavioural sequences increase the
  instantaneous hazard of entering an outbreak.
- **H2: Hierarchy** - Seniority / role modulates the strength of pre-cursors.
- **H3: Connection** - Bursts of networked interactions precede an outbreak

## Temporal sequence modelling - framing {.smaller}

- Consider a unified data stream generated by a hospital ward:

$$
\{(t_k, i_k, c_k, j_k, x_k)\}_{k=1}^N,
$$

- $t_k$: event datetime
- $i_k$: healtcare worker
- $c_k$: event category
- $j_k$: other person involved in event
- $x_k$: location

## Temporal sequence modelling - framing

- Assign temporal bins
- Engineer features
- Estimate at each time, $t$, the probability that the system will enter an
  outbreak within a fixed temporal horizon, $H$.
  - Logistic regression
  - GLMM

## Temporal sequence modelling - feature engineering {.smaller .scrollable}

- Number of people on shift a given time, $N_{staff}(t)$
- Binned staff time (mins/hours) - the number of mins/hours a HCW worked in a
  given temporal bin, $\sum_{i \in W} \mathrm{overlap_{mins}}(i, t)$
- Absence / understaffing indicator:

$$
A(t) = \frac{N_{rostered}(t) - N_{attended}(t)}{N_{rostered}}
$$

- Shift type, e.g. day vs night, weekday vs weekend
- Shift change indicator
- Interaction intensity:

$$
I(t) = \frac{N_{interactions}(t)}{N_{staff}(t)}
$$

- Total interaction count, $N_{interactions}(t)$
- Interactions per staff mins/hours:

$$
\frac{N_{interactions}}{\mathrm{binned\_staff\_hours}}
$$

- Unique patients
- Patients per worker concentration
- Gini of patients across workers
- Entropy of patients across workers
- Proportion of interactions that are already seen in the last $t$ time
- Counts of interactions by procedure category
- Proportion of interactions by procedure category
- Counts of high-risk interactions by procedure category
- Proportion of high-risk interactions by procedure category
- Total doors swipes
- Unique doors swiped
- Location entropy
- Network metrics:
  - Construct bipartite graph per unit time between HCWs and patients
  - Mean worker degree
  - Max worker degree
  - Size of largest component
  - Graph density

- GLMM candidate variables - random intercepts by:
  - Ward
  - Week / month
  - Shift type

- We can also think about a lot of these features from an "episode" perspective
  rather than considering a shift or any other arbitrary unit of time.
- An episode is defined as a segmented chunk of activity that is treated as a
  unit.
- We might consider a range of different types of episodes:
  - Shift episodes: Everything a HCW does between the rostered start and end of
    their shift.
  - Care / patient-visit episodes: A contiguous period of interactions with the
    same patient.
  - Movement episodes: A sequence of door events that begins when a worker
    leaves one zone and arrives (i.e. starts dwelling) in another.
  - Task episodes: A block of actions around a procedure type.
- Based on this, we can compute things like:
  - Number of episodes per hour
  - Average episode length
  - Number of unique patients per episode
  - Proportion of episodes that span multiple spaces / patients 

- Another avenue might be think of other ways to find more basic ways of
  integrating behavioural sequences into basic models:
  - Transition counts: How often do different sequential pairs of events occur
    in a given unit time?
  - This could very quickly become a very large set of variables and would very
    much depend on how we define our "alphabet" of states.

## {.center}

::: {.fragment}
But what about the sequence of events?
:::
::: {.fragment}
What about the space?
:::
::: {.fragment}
What about the social structure?
:::

## Temporal sequence modelling - methods

- Transformer-style models [@vaswani2017attention]
- Neural Hawkes process [@mei2017neural]
- Intensity-based RNNs [@du2016recurrent]
- Temporal GNNs [@rossi2020temporal]
- Spatio-temporal scan statistics [@kulldorff2007multivariate]

# References {.smaller .scrollable}

